# Generated by Django 4.1.4 on 2022-12-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ducan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='state',
        ),
    ]
